### ISSUE TITLE
1.4.0 checklist

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/HistoricizedMedicine#5]
- [ ] Leech culture jar
- [ ] Blood fluid
- [ ] Fleam
- [ ] Expand on some of the incomplete features
- [ ] Make various vanilla mobs and mobs that extend them have some consequences relating to this mod
