### ISSUE TITLE
1.3.8 checklist

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/HistoricizedMedicine#6]
- [ ] Fix orientation of stairs and chests in stands
- [ ] Add more villager trades
- [x] Expand chest loot
- [x] Fix worktables dropping two of themselves at once
- [x] Fix worktables not dropping items stored in them

**Comment by Sunconure11** [comment]
Changelog for this update so far:

Fixed worktables dropping additional copies of themselves
Expanded chest loot for stalls
