### ISSUE TITLE
1.3.9 Checklist

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/HistoricizedMedicine#9]
- [ ] Fix orientation of stairs and chests in stands
- [ ] Add more villager trades
- [ ] Add at least one new item, to see how feasible it is for me to add new content
- [ ] Fix chests sometimes dropping their contents into the streets
- [ ] Detect if honey is not implemented, and use an alternate loot table/equivalent to circumvent bugs.
- [ ] Update mappings

**Comment by Sunconure11** [comment]
Going to revisit 1.3.9 when Bewitchment pushes out it's first beta.

**Comment by Sunconure11** [comment]
Bewitchment is in closed alpha now, but I will wait a bit anyways
